# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build_test.yml

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Setup Yarn package manager
        run: |
          corepack enable
          yarn set version berry
          yarn install --immutable
      - run: yarn build
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.gns-science.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.gns-science.npmAlwaysAuth true
          yarn config set npmScopes.gns-science.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - run: yarn npm publish
          
          
          
